version: '3'
services:
  financenter:
    build: ./  
    restart: unless-stopped
    volumes:
      - $PWD/:/work
    depends_on:
      - db
    entrypoint: ['python','run.py']
  db:
    build: ./pgsql
    restart: unless-stopped
    volumes:
      # - ./pgsql/postgresqltuner_init.sh:/docker-entrypoint-initdb.d/00_postgresqltuner_init.sh
      - ./pgsql/init_db.sh:/docker-entrypoint-initdb.d/10_init_db.sh
    environment:
      - POSTGRES_PASSWORD=iG8ohh0ec6uh
      - POSTGRES_USER=findy
      - POSTGRES_DB=findy


